### ISSUE TITLE
Code Upgrade

### ISSUE THREAD

**Issue by kka-na** [inha-cvl/mobinha#11]
**PathPlanner**
upgrade Alter Path Planning 
- Avoid Obstacle

**Comment by kka-na** [comment]
## MORAI Linking
@maru-jang 

[MORAI planner]
https://github.com/inha-cvl/mobinha/blob/fec59208f87d476e337a158c0c7907db282deb97/tools/morai/gen_ros/scripts/mobinha_planner.py#L48
+
[MORAI transceiver]
https://github.com/inha-cvl/mobinha/blob/fec59208f87d476e337a158c0c7907db282deb97/selfdrive/car/morai_transceiver.py#L44

[NIRO transceiver]
https://github.com/inha-cvl/mobinha/blob/fec59208f87d476e337a158c0c7907db282deb97/selfdrive/car/niro_transceiver.py#L79

[SIMULATOR transceiver]
https://github.com/inha-cvl/mobinha/blob/fec59208f87d476e337a158c0c7907db282deb97/selfdrive/car/simulator_transceiver.py#L26

**Comment by kka-na** [comment]
## MORAI object linking

[![MORAI object linking with MobInhaTesting Video](http://img.youtube.com/vi/4LNmen-CZDo/0.jpg)](https://youtu.be/4LNmen-CZDo)

**Comment by kka-na** [comment]
## Information Tab Test
[![mobinha Information Tab Test](http://img.youtube.com/vi/X0VVaE_oijA/0.jpg)](https://youtu.be/X0VVaE_oijA)

**Comment by kka-na** [comment]
## Information Tab

**Last Distance**
[![MOBINHA Object Distance Testing Video](http://img.youtube.com/vi/8XFCwJqfAgA/0.jpg)](https://youtu.be/8XFCwJqfAgA)

**Forward Direction & Blinker **
[![MOBINHA Object Distance Testing Video](http://img.youtube.com/vi/tZFEegVPu1o/0.jpg)](https://youtu.be/tZFEegVPu1o)

**Comment by kka-na** [comment]
##  ROS Bag record with GUI

**Simple Record**
[![MOBINHA Record Visualize Video](http://img.youtube.com/vi/hf9D7SWM7sA/0.jpg)](https://youtu.be/hf9D7SWM7sA)

**Comment by kka-na** [comment]
##  MORAI Test

**Cut-in Test**
[![MOBINHA Cut-in test with MORAI](http://img.youtube.com/vi/UK8EsYljmT0/0.jpg)](https://youtu.be/UK8EsYljmT0)

**Traffic Light Linking**
[![MOBINHA Traffic Light Linking  test with MORAI](http://img.youtube.com/vi/37Jj-GsplDk/0.jpg)](https://youtu.be/37Jj-GsplDk)

**Comment by inha-cvl** [comment]
Upgrade over, need functionality modification or update

**Comment by kka-na** [comment]
##  MORAI Test

**Visualize Test**
[![MOBINHA Visualize test with MORAI(http://img.youtube.com/vi/fjlmK7vEk0Y/0.jpg)](https://youtu.be/fjlmK7vEk0Y)

**Comment by kka-na** [comment]
[ ] Visualize longitudinal planning with obstacle handler
