### ISSUE TITLE
Lateral Issues

### ISSUE THREAD

**Issue by inha-cvl** [inha-cvl/mobinha#31]
Steering is 🤮 : Improvement Idea) Goal : 10. Current : 0 -> Current : 5 -> Current : 8 -> Current : 9 -> Current : 10 (Little By Little) 
- [ ] Get current steer angle (CAN)
- [ ] Implement PID or other controller to go to target goal value 
- [ ] Implement test code (to test in-campus)
- [ ] TEST and TUNE

**Comment by kka-na** [comment]
![image](https://user-images.githubusercontent.com/69347961/223997183-ee6932de-e2dd-47ef-a0e1-c66a758e4d6b.png)

**Comment by inha-cvl** [comment]
change lane issue -> more smoothly

**Comment by kka-na** [comment]
![](https://blog.comma.ai/img/0812_release/new_follow.png)

**Comment by inha-cvl** [comment]
still unstable when changing lane

**Comment by inha-cvl** [comment]
move strange when starting
