### ISSUE TITLE
Longitudinal planning modifying

### ISSUE THREAD

**Issue by kka-na** [inha-cvl/mobinha#36]

**Comment by kka-na** [comment]
![image](https://user-images.githubusercontent.com/69347961/223001281-61cc3f27-ab2a-40c2-9bd0-5128d2be04cd.png)

![image](https://user-images.githubusercontent.com/69347961/223001300-e5d59696-896c-414c-938a-d50affed9e1e.png)

**Comment by inha-cvl** [comment]
https://github.com/inha-cvl/mobinha/blob/3570ef21235f53c0968399e54051c5eee1ec82fe/selfdrive/planning/longitudinal_planner.py#L65-L105

udpated to simple velocity plan using sigmoid logit probability function

**Comment by kka-na** [comment]
![](https://blog.comma.ai/img/0812_release/new_follow.png)

**Comment by inha-cvl** [comment]
when curve left, too slow because deaccel by curvature

**Comment by maru-jang** [comment]
plaaning 단에 서 tracking t-1, t 비교 X 여러 프레임 ex 5프레임 누적 평균. 임계치 이상 차이 시 다시 초기화.
로깅해서 쓰자. 
6-7 Hz 150ms 2개가 임계치 넘으면..,., 
차가 확확변할리는 별로 없으니, 확 느려지는거.
연구와개발 간극.

**Comment by maru-jang** [comment]
가까운 장애물 기준으로 속도 결정하는데 
나도 빠르고 앞차도 빠르면 약 40m 떨어져있다고 치면 ㅇ이렇게 달리는중에 정지선이나 목적지가 100m~0m 될때 멈춰주는 속도가 있는데 그걸 무시하고 100~40m 구간에서는 빠른 걸 유지하지 앞차 acc하는 중이라 그래서 40m~0m까지 정지선 목적지에 멈추려고해도 너무 급격히 멈춰. 
그래서 정지선이나 목적지는 무조건 100m남으면 속도결정을 그걸로 바꿔줘야하나 싶은?
@kka-na

**Comment by maru-jang** [comment]
10hz로 낮추니 곡률감속에서 감속제대로 못함

**Comment by kka-na** [comment]
- [ ] 차선 변경 할 때 곡률 봐버리고 감속해 버리는거
- [ ] 좌회전 할 때 너무 쫄보처럼 곡률 봐버리는거
