### ISSUE TITLE
Comfort ACC

### ISSUE THREAD

**Issue by maru-jang** [inha-cvl/mobinha#41]

**Comment by maru-jang** [comment]
내 차 속도가 빠를 때 곡률보고 미리감속하면 좋을 것 같아서 curv 식 변경

**Comment by maru-jang** [comment]
link에 미리 횡단보도 저장할수있게고민

**Comment by inha-cvl** [comment]
https://github.com/inha-cvl/mobinha/blob/3570ef21235f53c0968399e54051c5eee1ec82fe/selfdrive/planning/libs/planner_utils.py#L331-L353

dynamic curvature deaccelaration logic
