### ISSUE TITLE
Traffic Light obstacle handling logic

### ISSUE THREAD

**Issue by inha-cvl** [inha-cvl/mobinha#43]
Always stop on stop-line -> when green, green-arrow go

**Comment by inha-cvl** [comment]
Add testing module ( Send dummy bounding box message )

**Comment by maru-jang** [comment]
링크가 긴 곳에서 횡단보도 있는 구역에서 초록불보고 지나가도 링크id가 그대로라서 정지선 정보가 남아있는데 남은거리가 음수라서 디텍션이 안되면 정지하려고함.!!!!!!!!!!!!!!!!!! ************************
