### ISSUE TITLE
Forward obstacle from LiDAR

### ISSUE THREAD

**Issue by inha-cvl** [inha-cvl/mobinha#44]
safety margin distance modification

**Comment by kka-na** [comment]
https://github.com/commaai/openpilot/blob/7c9fa91fb87d4ba2c97d6b08971e86827a6c38cf/selfdrive/controls/lib/longitudinal_mpc_lib/long_mpc.py#L62


![](https://blog.comma.ai/img/0812_release/new_stop.png)

**Comment by kka-na** [comment]
![image](https://user-images.githubusercontent.com/69347961/224965832-fbe99d70-73fb-4839-9ad1-664fda6995eb.png)

**Comment by inha-cvl** [comment]
ACC : parameter tuning

**Comment by inha-cvl** [comment]
find excellent gain!
