### ISSUE TITLE
Lane Change Logic 

### ISSUE THREAD

**Issue by kka-na** [inha-cvl/mobinha#46]

**Comment by kka-na** [comment]
## Lane Change with BSD

[![Lane Change Testing Video](http://img.youtube.com/vi/SiZMGvAFtHU/0.jpg)](https://youtu.be/SiZMGvAFtHU)

**Comment by kka-na** [comment]
Out of Index Exception 처리

**Comment by maru-jang** [comment]
def limit_steer_change(self, steer):
        steer_diff = steer - self.prev_steer
        if abs(steer_diff) > 10:
            steer = self.prev_steer + (10 if steer_diff > 0 else -10)
        self.prev_steer = steer
        return steer

**Comment by kka-na** [comment]
**Smooth Path**

def run() 전에 아래 함수 추가 

```
 def delete_node_for_smooth_path(self, non_intp_path, non_intp_id, head_lane_ids):
        
        before_n = non_intp_id[0].split('_')[0]
        for i, n in enumerate(non_intp_id):
            splited_id = n.split('_')[0]
            if splited_id != before_n :
                my_neighbor_id = get_my_neighbor(self.lmap.lanelets, before_n)
                if not compare_id(splited_id, my_neighbor_id):
                    del non_intp_path[i]
                    del non_intp_id[i]
                before_n = splited_id
```

if non_intp_path is not None:
전에 아래 줄 추가 

```
self.delete_node_for_smooth_path(non_intp_path, non_intp_id, head_lane_ids)
```
